# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 6) do

  create_table "AbsenDosen", :id => false, :force => true do |t|
    t.column "IDDosen",      :string,   :limit => 10
    t.column "TglKunjungan", :datetime
  end

  add_index "AbsenDosen", ["IDDosen"], :name => "IDDosen"

  create_table "Buku", :force => true do |t|
    t.column "InfoIDBuku",    :string,   :limit => 9
    t.column "IDBuku",        :integer,  :limit => 10
    t.column "Cetakan",       :string,   :limit => 10
    t.column "Edisi",         :string,   :limit => 6
    t.column "TanggalMasuk",  :datetime
    t.column "TanggalKeluar", :datetime
    t.column "NoRak",         :string,   :limit => 12
    t.column "Harga",         :decimal,                :precision => 19, :scale => 4
    t.column "SumberDana",    :string,   :limit => 30
    t.column "TahunAnggaran", :string,   :limit => 5
  end

  add_index "Buku", ["IDBuku"], :name => "BookID"
  add_index "Buku", ["InfoIDBuku"], :name => "BookInfoID"
  add_index "Buku", ["id"], :name => "id"

  create_table "CD", :id => false, :force => true do |t|
    t.column "InfoIDCD",      :string,   :limit => 5,  :default => "", :null => false
    t.column "IDCD",          :string,   :limit => 5,  :default => "", :null => false
    t.column "TanggalMasuk",  :datetime
    t.column "TanggalKeluar", :datetime
    t.column "Lokasi",        :string,   :limit => 50
    t.column "Status",        :string,   :limit => 20
  end

  add_index "CD", ["IDCD"], :name => "BookID"
  add_index "CD", ["InfoIDCD"], :name => "BookInfoID"

  create_table "CDBuku", :id => false, :force => true do |t|
    t.column "InfoIDBuku", :string, :limit => 5, :default => "", :null => false
    t.column "InfoIDCD",   :string, :limit => 5, :default => "", :null => false
  end

  add_index "CDBuku", ["InfoIDBuku"], :name => "BookInfoID"
  add_index "CDBuku", ["InfoIDCD"], :name => "CassetteInfoID"

  create_table "DetailKTI", :id => false, :force => true do |t|
    t.column "InfoIDKTI",           :string, :limit => 9,   :default => "", :null => false
    t.column "ParameterPenelitian", :string, :limit => 100
    t.column "Ilustrasi",           :string, :limit => 100
    t.column "Hasil Penelitian",    :string, :limit => 150
  end

  create_table "Dosen", :force => true do |t|
    t.column "IDDosen",     :string, :limit => 10
    t.column "Nama",        :string, :limit => 40
    t.column "Pangkat",     :string, :limit => 20
    t.column "Golongan",    :string, :limit => 5
    t.column "Ruang",       :string, :limit => 2
    t.column "Alamat",      :string, :limit => 70
    t.column "AlamateMail", :string, :limit => 20
    t.column "Photo",       :binary
    t.column "TandaTangan", :binary
  end

  add_index "Dosen", ["Nama"], :name => "Name", :unique => true
  add_index "Dosen", ["IDDosen"], :name => "TeacherID", :unique => true
  add_index "Dosen", ["id"], :name => "id"

  create_table "InfoBuku", :force => true do |t|
    t.column "InfoIDBuku",      :string, :limit => 9
    t.column "Judul",           :string, :limit => 150
    t.column "Kategori",        :string, :limit => 5
    t.column "NoUrut",          :string, :limit => 7
    t.column "NoKlasifikasi",   :string, :limit => 15
    t.column "Penerbit",        :string, :limit => 100
    t.column "Kota",            :string, :limit => 15
    t.column "Tahun",           :string, :limit => 4
    t.column "Kolasi",          :string, :limit => 50
    t.column "Seri",            :string, :limit => 75
    t.column "ISBN",            :string, :limit => 15
    t.column "PengarangI",      :string, :limit => 35
    t.column "PengarangII",     :string, :limit => 30
    t.column "PengarangIII",    :string, :limit => 30
    t.column "AlihBahasaI",     :string, :limit => 30
    t.column "AlihBahasaII",    :string, :limit => 30
    t.column "EditorI",         :string, :limit => 30
    t.column "EditorII",        :string, :limit => 30
    t.column "EditorIII",       :string, :limit => 30
    t.column "JudulAsli",       :string, :limit => 150
    t.column "SubyekI",         :string, :limit => 50
    t.column "SubyekII",        :string, :limit => 50
    t.column "SubyekIII",       :string, :limit => 50
    t.column "Askeb",           :string, :limit => 30
    t.column "SemuaPengarang",  :string, :limit => 150
    t.column "JumlahEksemplar", :string, :limit => 10
    t.column "KataKunci",       :string
    t.column "Lokasi",          :string, :limit => 25
    t.column "JenisBuku",       :string, :limit => 15
    t.column "Golongan",        :string, :limit => 10
    t.column "Bibliografi",     :string, :limit => 30
    t.column "Indeks",          :string, :limit => 25
    t.column "GambarBuku",      :binary
    t.column "Description",     :text
    t.column "image_filename",  :string
  end

  add_index "InfoBuku", ["InfoIDBuku"], :name => "BookInfoID"
  add_index "InfoBuku", ["Judul"], :name => "DataBookBookTitle"
  add_index "InfoBuku", ["id"], :name => "id"

  create_table "InfoCD", :id => false, :force => true do |t|
    t.column "InfoIDCD",     :string, :limit => 5,   :default => "", :null => false
    t.column "Judul",        :string, :limit => 150
    t.column "Deskripsi",    :string
    t.column "SubyekI",      :string, :limit => 25
    t.column "SubyekII",     :string, :limit => 25
    t.column "SubyekIII",    :string, :limit => 25
    t.column "Panjang",      :string, :limit => 10
    t.column "Penerbit",     :string, :limit => 50
    t.column "Kota",         :string, :limit => 15
    t.column "Tahun",        :string, :limit => 4
    t.column "Unit",         :string, :limit => 10
    t.column "PengarangI",   :string, :limit => 30
    t.column "PengarangII",  :string, :limit => 30
    t.column "PengarangIII", :string, :limit => 30
    t.column "ISBN",         :string, :limit => 15
    t.column "Note",         :string
  end

  add_index "InfoCD", ["InfoIDCD"], :name => "CassetteInfoID"

  create_table "InfoKTI", :force => true do |t|
    t.column "InfoIDKTI",        :string, :limit => 9
    t.column "Tipe",             :string, :limit => 3
    t.column "NoUrut",           :string, :limit => 4
    t.column "Judul",            :string, :limit => 160
    t.column "TempatPenelitian", :string, :limit => 150
    t.column "PengarangI",       :string, :limit => 35
    t.column "Inisial",          :string, :limit => 3
    t.column "PAkademik",        :string, :limit => 40
    t.column "SubyekI",          :string, :limit => 35
    t.column "SubyekII",         :string, :limit => 35
    t.column "SubyekIII",        :string, :limit => 35
    t.column "Tahun",            :string, :limit => 4
    t.column "Program",          :string, :limit => 10
    t.column "NoRak",            :string, :limit => 10
    t.column "JumlahEksemplar",  :string, :limit => 6
    t.column "SemuaPengarang",   :string, :limit => 35
    t.column "KataKunci",        :string, :limit => 50
  end

  add_index "InfoKTI", ["NoUrut"], :name => "NoUrut", :unique => true
  add_index "InfoKTI", ["id"], :name => "id"
  add_index "InfoKTI", ["Judul"], :name => "Judul"

  create_table "InfoKaset", :id => false, :force => true do |t|
    t.column "InfoIDKaset",  :string, :limit => 5,   :default => "", :null => false
    t.column "Judul",        :string, :limit => 150
    t.column "Deskripsi",    :string
    t.column "SubyekI",      :string, :limit => 25
    t.column "SubyekII",     :string, :limit => 25
    t.column "SubyekIII",    :string, :limit => 25
    t.column "Panjang",      :string, :limit => 10
    t.column "Penerbit",     :string, :limit => 50
    t.column "Kota",         :string, :limit => 15
    t.column "Tahun",        :string, :limit => 4
    t.column "Unit",         :string, :limit => 10
    t.column "PengarangI",   :string, :limit => 30
    t.column "PengarangII",  :string, :limit => 30
    t.column "PengarangIII", :string, :limit => 30
    t.column "ISBN",         :string, :limit => 15
    t.column "Note",         :string
  end

  add_index "InfoKaset", ["InfoIDKaset"], :name => "CassetteInfoID"

  create_table "InfoVideo", :id => false, :force => true do |t|
    t.column "InfoIDVideo",  :string, :limit => 5,   :default => "", :null => false
    t.column "Judul",        :string, :limit => 150
    t.column "Deskripsi",    :string, :limit => 200
    t.column "SubyekI",      :string, :limit => 25
    t.column "SubyekII",     :string, :limit => 25
    t.column "SubyekIII",    :string, :limit => 25
    t.column "Panjang",      :string, :limit => 10
    t.column "Penerbit",     :string, :limit => 50
    t.column "Kota",         :string, :limit => 15
    t.column "Tahun",        :string, :limit => 4
    t.column "Unit",         :string, :limit => 10
    t.column "PengarangI",   :string, :limit => 30
    t.column "PengarangII",  :string, :limit => 30
    t.column "PengarangIII", :string, :limit => 30
    t.column "ISBN",         :string, :limit => 15
    t.column "Note",         :string
  end

  add_index "InfoVideo", ["InfoIDVideo"], :name => "VideoInfoID"

  create_table "KTI", :id => false, :force => true do |t|
    t.column "InfoIDKTI",     :string,   :limit => 9
    t.column "IDKTI",         :integer,  :limit => 10
    t.column "TanggalMasuk",  :datetime
    t.column "TanggalKeluar", :datetime
    t.column "NoRak",         :string,   :limit => 10
  end

  add_index "KTI", ["IDKTI"], :name => "BookID"

  create_table "KartuKatalog", :id => false, :force => true do |t|
    t.column "InfoIDBuku", :string, :limit => 9, :default => "", :null => false
    t.column "IDBuku",     :string, :limit => 5
  end

  add_index "KartuKatalog", ["InfoIDBuku"], :name => "BookInfoID"
  add_index "KartuKatalog", ["IDBuku"], :name => "IDBuku"

  create_table "Kaset", :id => false, :force => true do |t|
    t.column "InfoIDKaset",   :string,   :limit => 5,  :default => "", :null => false
    t.column "KasetID",       :string,   :limit => 5,  :default => "", :null => false
    t.column "TanggalMasuk",  :datetime
    t.column "TanggalKeluar", :datetime
    t.column "Lokasi",        :string,   :limit => 50
    t.column "Status",        :string,   :limit => 20
  end

  add_index "Kaset", ["KasetID"], :name => "BookID"
  add_index "Kaset", ["InfoIDKaset"], :name => "BookInfoID"

  create_table "KasetBuku", :id => false, :force => true do |t|
    t.column "InfoIDBuku",  :string, :limit => 5, :default => "", :null => false
    t.column "InfoKasetID", :string, :limit => 5, :default => "", :null => false
  end

  add_index "KasetBuku", ["InfoIDBuku"], :name => "BookInfoID"
  add_index "KasetBuku", ["InfoKasetID"], :name => "CassetteInfoID"

  create_table "KategoriBuku", :id => false, :force => true do |t|
    t.column "Kategori", :string, :limit => 10
  end

  add_index "KategoriBuku", ["Kategori"], :name => "Category"

  create_table "Kelas", :id => false, :force => true do |t|
    t.column "IDSiswa", :string, :limit => 15, :default => "", :null => false
    t.column "Tingkat", :string, :limit => 7
    t.column "Date",    :string, :limit => 50
    t.column "Time",    :string, :limit => 50
  end

  add_index "Kelas", ["Date"], :name => "ClassCourseDate"
  add_index "Kelas", ["Tingkat"], :name => "ClassCourseTermNo"
  add_index "Kelas", ["Time"], :name => "ClassCourseTime"

  create_table "Kunjungan", :force => true do |t|
    t.column "IDDosen",      :string,   :limit => 10
    t.column "IDMahasiswa",  :string,   :limit => 10
    t.column "TglKunjungan", :datetime
  end

  add_index "Kunjungan", ["id"], :name => "id"
  add_index "Kunjungan", ["IDDosen"], :name => "IDDosen"
  add_index "Kunjungan", ["IDMahasiswa"], :name => "StudentID"

  create_table "LabelBuku", :id => false, :force => true do |t|
    t.column "InfoIDBuku", :string,  :limit => 9
    t.column "IDBuku",     :integer, :limit => 10
  end

  add_index "LabelBuku", ["InfoIDBuku"], :name => "BookInfoID"
  add_index "LabelBuku", ["IDBuku"], :name => "LabelBookcopy"

  create_table "LabelCD", :id => false, :force => true do |t|
    t.column "InfoIDCD", :string, :limit => 5
    t.column "Copy",     :string, :limit => 6
  end

  add_index "LabelCD", ["InfoIDCD"], :name => "BookInfoID"

  create_table "LabelKTI", :id => false, :force => true do |t|
    t.column "InfoIDKTI", :string,  :limit => 9
    t.column "IDKTI",     :integer, :limit => 10
  end

  add_index "LabelKTI", ["InfoIDKTI"], :name => "BookInfoID"
  add_index "LabelKTI", ["IDKTI"], :name => "LabelBookcopy"

  create_table "LabelKaset", :id => false, :force => true do |t|
    t.column "InfoIDKaset", :string, :limit => 5
    t.column "Copy",        :string, :limit => 20
  end

  add_index "LabelKaset", ["InfoIDKaset"], :name => "BookInfoID"
  add_index "LabelKaset", ["Copy"], :name => "LabelBookcopy"

  create_table "LabelVideo", :id => false, :force => true do |t|
    t.column "InfoIDVideo", :string, :limit => 5
    t.column "Copy",        :string, :limit => 20
  end

  add_index "LabelVideo", ["InfoIDVideo"], :name => "BookInfoID"
  add_index "LabelVideo", ["Copy"], :name => "LabelBookcopy"

  create_table "Mahasiswa", :force => true do |t|
    t.column "IDMahasiswa", :string,   :limit => 10
    t.column "Nama",        :string,   :limit => 35
    t.column "Alamat",      :string,   :limit => 70
    t.column "AlamatEmail", :string,   :limit => 30
    t.column "TempatLahir", :string,   :limit => 25
    t.column "TglLahir",    :datetime
    t.column "NoTelpRumah", :string,   :limit => 20
    t.column "NoHp",        :string,   :limit => 13
    t.column "Hobby",       :string,   :limit => 60
    t.column "Angkatan",    :string,   :limit => 5
    t.column "Tahun",       :string,   :limit => 12
    t.column "Tingkat",     :string,   :limit => 5
    t.column "Semester",    :string,   :limit => 5
    t.column "Photo",       :binary
    t.column "Register",    :integer,  :limit => 3
  end

  add_index "Mahasiswa", ["Nama"], :name => "Name", :unique => true
  add_index "Mahasiswa", ["IDMahasiswa"], :name => "StudentID", :unique => true
  add_index "Mahasiswa", ["id"], :name => "id"

  create_table "SirkulasiDosen", :force => true do |t|
    t.column "IDDosen",       :string,   :limit => 10
    t.column "InfoIDBuku",    :string,   :limit => 9
    t.column "IDBuku",        :integer,  :limit => 10
    t.column "TglPinjam",     :datetime
    t.column "TglHrsKembali", :datetime
    t.column "Belum",         :boolean,                :null => false
    t.column "Kembali",       :boolean,                :null => false
  end

  add_index "SirkulasiDosen", ["id"], :name => "id"
  add_index "SirkulasiDosen", ["IDBuku"], :name => "IDBuku"
  add_index "SirkulasiDosen", ["IDDosen"], :name => "IDDosen"
  add_index "SirkulasiDosen", ["InfoIDBuku"], :name => "InfoIDBuku"

  create_table "SirkulasiDosen1", :force => true do |t|
    t.column "IDDosen",    :string,   :limit => 10
    t.column "InfoIDBuku", :string,   :limit => 9
    t.column "IDBuku",     :integer,  :limit => 10
    t.column "TglPinjam",  :datetime
    t.column "TglKembali", :datetime
  end

  add_index "SirkulasiDosen1", ["id"], :name => "id"
  add_index "SirkulasiDosen1", ["IDBuku"], :name => "IDBuku"
  add_index "SirkulasiDosen1", ["IDDosen"], :name => "IDDosen"
  add_index "SirkulasiDosen1", ["InfoIDBuku"], :name => "InfoIDBuku"

  create_table "SirkulasiMahasiswa", :force => true do |t|
    t.column "IDMahasiswa",   :string,   :limit => 10
    t.column "InfoIDBuku",    :string,   :limit => 9
    t.column "IDBuku",        :integer,  :limit => 10, :null => false
    t.column "TglPinjam",     :datetime
    t.column "TglHrsKembali", :datetime
    t.column "Kembali",       :boolean,                :null => false
    t.column "Belum",         :boolean,                :null => false
  end

  create_table "SirkulasiMahasiswa1", :force => true do |t|
    t.column "IDMahasiswa", :string,   :limit => 10
    t.column "InfoIDBuku",  :string,   :limit => 9
    t.column "IDBuku",      :integer,  :limit => 10, :null => false
    t.column "TglPinjam",   :datetime
    t.column "TglKembali",  :datetime
  end

  add_index "SirkulasiMahasiswa1", ["id"], :name => "PrimaryKey1", :unique => true
  add_index "SirkulasiMahasiswa1", ["id"], :name => "id"
  add_index "SirkulasiMahasiswa1", ["IDBuku"], :name => "IDBuku"
  add_index "SirkulasiMahasiswa1", ["IDMahasiswa"], :name => "IDSiswa"
  add_index "SirkulasiMahasiswa1", ["InfoIDBuku"], :name => "InfoIDBuku"

  create_table "Video", :id => false, :force => true do |t|
    t.column "InfoIDVideo",   :string,   :limit => 5,  :default => "", :null => false
    t.column "IDVideo",       :string,   :limit => 5,  :default => "", :null => false
    t.column "TanggalMasuk",  :datetime
    t.column "TanggalKeluar", :datetime
    t.column "Lokasi",        :string,   :limit => 50
    t.column "Status",        :string,   :limit => 20
  end

  add_index "Video", ["IDVideo"], :name => "BookID"
  add_index "Video", ["InfoIDVideo"], :name => "BookInfoID"

  create_table "VideoBuku", :id => false, :force => true do |t|
    t.column "InfoIDBuku",  :string, :limit => 5, :default => "", :null => false
    t.column "InfoVideoID", :string, :limit => 5, :default => "", :null => false
  end

  add_index "VideoBuku", ["InfoIDBuku"], :name => "BookInfoID"
  add_index "VideoBuku", ["InfoVideoID"], :name => "CassetteInfoID"

  create_table "articles", :force => true do |t|
    t.column "title",       :string
    t.column "body",        :text
    t.column "author_name", :string
  end

  create_table "journals", :force => true do |t|
    t.column "title",       :string
    t.column "discription", :text
    t.column "author_name", :string
  end

  create_table "users", :force => true do |t|
    t.column "login",                     :string
    t.column "email",                     :string
    t.column "crypted_password",          :string,   :limit => 40
    t.column "salt",                      :string,   :limit => 40
    t.column "created_at",                :datetime
    t.column "updated_at",                :datetime
    t.column "remember_token",            :string
    t.column "remember_token_expires_at", :datetime
  end

end
